pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - files~=^builds/
      - files~=^changelogs/
      - check-success=Validate json files
      - "#files=2"
    actions:
      merge:
        method: merge
